### ISSUE TITLE
rachel doesn't know what github issues are

### ISSUE THREAD

**Issue by dannyhyatt** [medude/ftc_app#1]
other than the fact that it's sad, it's still an issue how rachel doesn't know about it. github's issue trackers are among the best, which is why people USE THEM.

**Comment by dannyhyatt** [comment]
i'll go solve it rn

**Comment by itsmerachel** [comment]
what the shit

**Comment by dannyhyatt** [comment]
google it

**Comment by itsmerachel** [comment]
uuuuuuuuuuuUUUUGh
